INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'suresh@gmail.com', 'suresh', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'raju12@gmail.com', 'raju', 'USER');
INSERT INTO USERS VALUES (NEXT VALUE FOR HIBERNATE_SEQUENCE, 'rajat@gmail.com', 'rajat', 'ADMIN');